import AuthNav from "./components/AuthNav";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import { AuthProvider } from "./providers";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body className={inter.className}>
  <AuthProvider>
    <header className="p-4 border-b">
      <nav className="flex gap-6">
        <a href="/" className="hover:underline">Home</a>
        <a href="/tournaments" className="hover:underline">Tournaments</a>
        <a href="/calendar" className="hover:underline">Calendar</a>
        <a href="/submit" className="hover:underline">Submit</a>
        <a href="/dashboard" className="hover:underline">Dashboard</a>
        <a href="/schedule" className="hover:underline">My Schedule</a>
        <AuthNav />
      </nav>
    </header>

    {children}
  </AuthProvider>
</body>

    </html>
  );
}
